import turtle as trtl 
pk = trtl.Turtle()

pk.penup()
pk.pencolor("green")
pk.pensize(3)
pk.goto(-39,268)
pk.pendown()
pk.begin_fill()
pk.fillcolor("green")
pk.forward(23)
pk.circle(37,steps=4)
pk.end_fill()

pk.penup()
pk.pencolor("orange")
pk.goto(-40,-100)
pk.pendown()
pk.begin_fill()
pk.fillcolor("orange")
pk.circle(200)
pk.end_fill()

pk.penup()
pk.pencolor("black")
pk.goto(-120,148)
pk.pendown()
pk.begin_fill()
pk.fillcolor("black")
pk.circle(40)
pk.end_fill()

pk.penup()
pk.pencolor("black")
pk.goto(58,146)
pk.pendown()
pk.begin_fill()
pk.fillcolor("black")
pk.circle(40)
pk.end_fill()

pk.penup()
pk.pencolor("white")
pk.goto(-148,170)
pk.pendown()
pk.begin_fill()
pk.fillcolor("white")
pk.forward(57)
pk.left(128)
pk.forward(57)
pk.right(128)
pk.end_fill()

pk.penup()
pk.pencolor("white")
pk.goto(83,170)
pk.pendown()
pk.begin_fill()
pk.fillcolor("white")
pk.backward(57)
pk.right(128)
pk.backward(57)
pk.left(128)
pk.end_fill()

pk.penup()
pk.pencolor("black")
pk.pensize(5)
pk.goto(-148,262)
pk.pendown()
pk.right(20)
pk.forward(21)
pk.right(20)
pk.forward(21)
pk.left(10)
pk.forward(30)

pk.penup()
pk.pencolor("black")
pk.pensize(5)
pk.goto(80,242)
pk.pendown()
pk.left(20)
pk.backward(35)
pk.left(40)
pk.backward(31)
pk.right(10)
pk.backward(30)


pk.penup()
pk.pencolor("black")
pk.pensize(3)
pk.goto(-96,61)
pk.pendown()
pk.begin_fill()
pk.fillcolor("black")
pk.right(18)
pk.forward(159)
pk.right(112)
pk.forward(73)
pk.left(32)
pk.forward(30)
pk.right(153)
pk.forward(40)
pk.left(50)
pk.forward(80)
pk.left(60)
pk.forward(52)
pk.right(92)
pk.forward(48)
pk.right(38)
pk.forward(100)
pk.right(132)
pk.forward(53)
pk.left(30)
pk.forward(26)
pk.end_fill()


wn = trtl.Screen()
wn.mainloop()